# Sources at:
# - https://github.com/tbayaa/scss-lint/blob/master/.scss-lint.yml
# - http://sasstools.github.io/make-sass-lint-config/

files:
  ignore:
    - '**/nifty/*'
    - '**/nifty-override/*'
options:
  formatter: stylish
  merge-default-rules: true

rules:
  bem-depth: 1
#  border-zero:
#    - 1
#    - convention: none
  brace-style:
    - 1
    - allow-single-line: false
  class-name-format:
    - 1
    - convention: ^(?!js-).*
      convention-explanation: should not be written in the form js-*
#  clean-import-paths:
#    - 1
#    - filename-extension: false
#      leading-underscore: false
#  empty-line-between-blocks:
#    - 1
#    - ignore-single-line-rulesets: true
  extends-before-declarations: 0
  extends-before-mixins: 0
#  final-newline:
#    - 1
#    - include: true
  force-attribute-nesting: 0
  force-element-nesting: 0
  force-pseudo-nesting: 0
#  function-name-format:
#    - 1
#    - allow-leading-underscore: true
#      convention: hyphenatedlowercase
#  hex-length:
#    - 1
#    - style: short
#  hex-notation:
#    - 1
#    - style: lowercase
#  id-name-format:
#    - 1
#    - convention: hyphenatedlowercase
  indentation:
    - 1
    - size: 4
  leading-zero: 0
#  mixin-name-format:
#    - 1
#    - allow-leading-underscore: true
#    convention: hyphenatedlowercase
  mixins-before-declarations: 0
#  nesting-depth:
#    - 1
#    - max-depth: 3
#  no-color-keywords: 1
#  no-color-literals: 1
#  no-css-comments: 1
#  no-debug: 1
#  no-duplicate-properties: 1
#  no-empty-rulesets: 1
  no-extends: 0
#  no-ids: 1
#  no-important: 1
#  no-invalid-hex: 1
#  no-mergeable-selectors: 1
#  no-misspelled-properties:
#    - 1
#    - extra-properties: []
  no-qualifying-elements: 0
#  no-trailing-zero: 1
#  no-transition-all: 0
#  no-url-protocols: 1
#  no-vendor-prefixes:
#   - 1
#   - additional-identifiers: []
#     excluded-identifiers: []
#  placeholder-in-extend: 1
  placeholder-name-format:
    - 1
    - convention: hyphenatedbem
  property-sort-order: 0
#  property-units:
#    - 1
#    - global:
#        - ch
#        - em
#        - ex
#        - rem
#        - cm
#        - in
#        - mm
#        - pc
#        - pt
#        - px
#        - q
#        - vh
#        - vw
#        - vmin
#        - vmax
#        - deg
#        - grad
#        - rad
#        - turn
#        - ms
#        - s
#        - Hz
#        - kHz
#        - dpi
#        - dpcm
#        - dppx
#        - '%'
#      per-property: {}
  quotes:
    - 1
    - style: double
#  shorthand-values:
#    - 1
#    - allowed-shorthands:
#        - 1
#        - 2
#        - 3
#  single-line-per-selector: 1
#  space-after-bang:
#    - 1
#    - include: false
#  space-after-colon:
#    - 1
#    - include: true
#  space-after-comma:
#    - 1
#    - include: true
#  space-before-bang:
#    - 1
#    - include: true
#  space-before-brace:
#    - 1
#    - include: true
#  space-before-colon: 1
#  space-between-parens:
#    - 1
#    - include: false
#  trailing-semicolon: 1
#  url-quotes: 1
#  variable-for-property:
#    - 0
#    - properties: []
#  variable-name-format:
#    - 1
#    - allow-leading-underscore: true
#      convention: hyphenatedlowercase
#  zero-unit: 1
